# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_helptext_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 711)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 645))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelVarName_0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelVarName_0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelVarName_0.setObjectName("labelVarName_0")
        self.horizontalLayout.addWidget(self.labelVarName_0)
        self.labelHelpText_0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHelpText_0.sizePolicy().hasHeightForWidth())
        self.labelHelpText_0.setSizePolicy(sizePolicy)
        self.labelHelpText_0.setMaximumSize(QtCore.QSize(300, 16777215))
        self.labelHelpText_0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHelpText_0.setWordWrap(True)
        self.labelHelpText_0.setObjectName("labelHelpText_0")
        self.horizontalLayout.addWidget(self.labelHelpText_0)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelVarName_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelVarName_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelVarName_1.setObjectName("labelVarName_1")
        self.horizontalLayout_2.addWidget(self.labelVarName_1)
        self.labelHelpText_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHelpText_1.sizePolicy().hasHeightForWidth())
        self.labelHelpText_1.setSizePolicy(sizePolicy)
        self.labelHelpText_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHelpText_1.setObjectName("labelHelpText_1")
        self.horizontalLayout_2.addWidget(self.labelHelpText_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelVarName_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelVarName_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelVarName_2.setObjectName("labelVarName_2")
        self.horizontalLayout_3.addWidget(self.labelVarName_2)
        self.labelHelpText_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHelpText_2.sizePolicy().hasHeightForWidth())
        self.labelHelpText_2.setSizePolicy(sizePolicy)
        self.labelHelpText_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHelpText_2.setWordWrap(True)
        self.labelHelpText_2.setObjectName("labelHelpText_2")
        self.horizontalLayout_3.addWidget(self.labelHelpText_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBoxOk = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBoxOk.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxOk.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxOk.setObjectName("buttonBoxOk")
        self.verticalLayout.addWidget(self.buttonBoxOk)

        self.retranslateUi(Dialog)
        self.buttonBoxOk.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBoxOk.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelVarName_0.setText(_translate("Dialog", "Var 0"))
        self.labelHelpText_0.setText(_translate("Dialog", "Plasma shot number\', \'Detector channel number.\', \'Version number for these data.  Different sets of parameters for the same shot and detector channel are identified by their version number.  Shot, Channel, Version form the primary key and cannot be duplicated.\', \'Comment about this parameter set.\', \'Time integration interval (s) used for counting pulses.\', \'Lower pulse height histogram limit (V).\', \'Upper pulse height histogram limit (V).\', \'Number of bins for pulse height histogram.\', \'(True/False) Draw proton rate.\', \'(True/False) Draw triton rate.\', \'(True/False) Draw pulser rate.\', \'(True/False) Draw total rate.\', \'Lower pulse height limit for proton PID cut. \', \'Upper pulse height limit for proton PID cut. \', \'Lower pulse height limit for triton PID cut. \', \'Upper pulse height limit for triton PID cut. \', \'Lower pulse height limit for pulser PID cut. \', \'Upper pulse height limit for pulser PID cut. \', \'Maximal value of relative fitted pulse height uncertainty (in fraction) for signal to be accepted. This is a signal quality cut.  The larger the value to more pulses are accepted.\', \'Path to result file relative to root_directory (see"))
        self.labelVarName_1.setText(_translate("Dialog", "Var 1"))
        self.labelHelpText_1.setText(_translate("Dialog", "Help 1"))
        self.labelVarName_2.setText(_translate("Dialog", "Var 2"))
        self.labelHelpText_2.setText(_translate("Dialog", "Help 2"))
