# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelpDisplayDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(506, 409)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 481, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelColName = QtWidgets.QLabel(self.layoutWidget)
        self.labelColName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelColName.setObjectName("labelColName")
        self.horizontalLayout.addWidget(self.labelColName)
        self.labelHelpText = QtWidgets.QLabel(self.layoutWidget)
        self.labelHelpText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHelpText.setObjectName("labelHelpText")
        self.horizontalLayout.addWidget(self.labelHelpText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelColName_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelColName_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelColName_2.setObjectName("labelColName_2")
        self.horizontalLayout_2.addWidget(self.labelColName_2)
        self.labelHelpText_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelHelpText_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHelpText_2.setObjectName("labelHelpText_2")
        self.horizontalLayout_2.addWidget(self.labelHelpText_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelColName.setText(_translate("Dialog", "Col Name"))
        self.labelHelpText.setText(_translate("Dialog", "Help Result"))
        self.labelColName_2.setText(_translate("Dialog", "Col Name"))
        self.labelHelpText_2.setText(_translate("Dialog", "Help Result"))
