# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoLayouts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#WN this was changed by habe to allow a dynamic setup


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, db_data, dialog_size = (404,447), title = "Edit DB Row Values"):
        Dialog.setObjectName("Dialog")
        Dialog.resize(*dialog_size)
        self.title = title
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HL = []     # Hor.layout
        self.label = []  # lables
        self.LE = []     # line edits
        for i, data in enumerate(db_data):
            var_name = data[1] 
            horizontalLayout = QtWidgets.QHBoxLayout()
            horizontalLayout.setObjectName(f"HL_{var_name}_{i}")
            label = QtWidgets.QLabel(Dialog)
            label.setObjectName(f"label_{var_name}_{i}")
            horizontalLayout.addWidget(label)
            lineEdit = QtWidgets.QLineEdit(Dialog)
            lineEdit.setObjectName(f"lineEdit_{var_name}_{i}")
            horizontalLayout.addWidget(lineEdit)
            self.verticalLayout.addLayout(horizontalLayout)
            self.HL.append(horizontalLayout)
            self.label.append(label)
            self.LE.append(lineEdit)
            
        self.pushButtonSubmit = QtWidgets.QPushButton(Dialog)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.verticalLayout.addWidget(self.pushButtonSubmit)
        
        self.pushButtonDone = QtWidgets.QPushButton(Dialog)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.verticalLayout.addWidget(self.pushButtonDone)
        
        self.retranslateUi(Dialog, db_data)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, db_data):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", self.title))
        for i, data in enumerate(db_data):
            title_name = data[0]
            self.label[i].setText(_translate("Dialog", title_name))
        self.pushButtonSubmit.setText(_translate("Dialog", "Submit"))
        self.pushButtonDone.setText(_translate("Dialog", "Done"))