# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoLayouts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# This is a modified code.In contrast to LayoutsArray.py it also includes scroll bars.
# the development ui files are in the sandbox directory


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, db_data, dialog_size = (404,447), title = "Edit DB Row Values"):
        Dialog.setObjectName("Dialog")
        Dialog.resize(*dialog_size)
        self.verticalLayout_Dialog = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_Dialog.setObjectName("verticalLayout_Dialog")
        # scroll area to be defined here
        self.scrollArea_GroupBox = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_GroupBox.setWidgetResizable(True)
        self.scrollArea_GroupBox.setObjectName("scrollArea_GroupBox")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 515))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")      
        #
        self.title = title
        # setup groupbox for entries
        self.verticalLayout_ScrollArea = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_ScrollArea.setObjectName("verticalLayout_ScrollArea")
        self.groupBox_Dialog = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        # setup group box
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Dialog.sizePolicy().hasHeightForWidth())
        self.groupBox_Dialog.setSizePolicy(sizePolicy)
        self.groupBox_Dialog.setObjectName("groupBox_Dialog")
        self.verticalLayout_GroupBoxDialog = QtWidgets.QVBoxLayout(self.groupBox_Dialog)
        self.verticalLayout_GroupBoxDialog.setObjectName("verticalLayout_GroupBoxDialog")
        # prepare entries
        self.HL = []     # Hor.layout
        self.label = []  # lables
        self.LE = []     # line edits
        for i, data in enumerate(db_data):
            var_name = data[1] 
            horizontalLayout = QtWidgets.QHBoxLayout()
            horizontalLayout.setObjectName(f"HL_{var_name}_{i}")
            label = QtWidgets.QLabel(self.groupBox_Dialog)
            label.setObjectName(f"label_{var_name}_{i}")
            #print(f'setting up  : {i}, {var_name} ')
            # setup size policy for each entry
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
            horizontalLayout.addWidget(label)
            lineEdit = QtWidgets.QLineEdit(self.groupBox_Dialog)
            lineEdit.setObjectName(f"lineEdit_{var_name}_{i}")
            horizontalLayout.addWidget(lineEdit)
            self.verticalLayout_GroupBoxDialog.addLayout(horizontalLayout)
            self.HL.append(horizontalLayout)
            self.label.append(label)
            self.LE.append(lineEdit)
            
        self.pushButtonSubmit = QtWidgets.QPushButton(Dialog)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.verticalLayout_GroupBoxDialog.addWidget(self.pushButtonSubmit)
        
        self.pushButtonDone = QtWidgets.QPushButton(Dialog)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.verticalLayout_GroupBoxDialog.addWidget(self.pushButtonDone)
        # done with the content add to dialog
        self.verticalLayout_ScrollArea.addWidget(self.groupBox_Dialog)
        self.scrollArea_GroupBox.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_Dialog.addWidget(self.scrollArea_GroupBox)
        
        self.retranslateUi(Dialog, db_data)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, db_data):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", self.title))
        for i, data in enumerate(db_data):
            title_name = data[0]
            self.label[i].setText(_translate("Dialog", title_name))
        self.pushButtonSubmit.setText(_translate("Dialog", "Submit"))
        self.pushButtonDone.setText(_translate("Dialog", "Done"))