!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.20.3)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_lfitm1_getdims_x_p(r,s,f2pysetdata,flag)
      use lfitm1, only: d => x_p

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_x_p
      subroutine f2py_lfitm1_getdims_lista(r,s,f2pysetdata,flag)
      use lfitm1, only: d => lista

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_lista
      subroutine f2py_lfitm1_getdims_a(r,s,f2pysetdata,flag)
      use lfitm1, only: d => a

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_a
      subroutine f2py_lfitm1_getdims_covar(r,s,f2pysetdata,flag)
      use lfitm1, only: d => covar

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_covar
      subroutine f2py_lfitm1_getdims_mat(r,s,f2pysetdata,flag)
      use lfitm1, only: d => mat

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_mat
      subroutine f2py_lfitm1_getdims_matinv(r,s,f2pysetdata,flag)
      use lfitm1, only: d => matinv

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_matinv
      subroutine f2py_lfitm1_getdims_beta(r,s,f2pysetdata,flag)
      use lfitm1, only: d => beta

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_beta
      subroutine f2py_lfitm1_getdims_afunc(r,s,f2pysetdata,flag)
      use lfitm1, only: d => afunc

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_afunc
      subroutine f2py_lfitm1_getdims_ipiv(r,s,f2pysetdata,flag)
      use lfitm1, only: d => ipiv

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_ipiv
      subroutine f2py_lfitm1_getdims_indxr(r,s,f2pysetdata,flag)
      use lfitm1, only: d => indxr

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_indxr
      subroutine f2py_lfitm1_getdims_indxc(r,s,f2pysetdata,flag)
      use lfitm1, only: d => indxc

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_lfitm1_getdims_indxc
      subroutine f2pywrap_lfitm1_init_all (al, bl, xp, n_peaks, n_order,&
     & vary_code, istat, f2py_xp_d0, f2py_vary_code_d0)
      use lfitm1, only : init_all
      real(kind=8) al
      real(kind=8) bl
      integer n_peaks
      integer n_order
      integer istat
      integer f2py_xp_d0
      integer f2py_vary_code_d0
      real(kind=8) xp(f2py_xp_d0)
      integer vary_code(f2py_vary_code_d0)
      call init_all(al, bl, xp, n_peaks, n_order, vary_code, istat)
      end subroutine f2pywrap_lfitm1_init_all
      subroutine f2pywrap_lfitm1_init_fit (vary_code, f2py_vary_code_d0)
      use lfitm1, only : init_fit
      integer f2py_vary_code_d0
      integer vary_code(f2py_vary_code_d0)
      call init_fit(vary_code)
      end subroutine f2pywrap_lfitm1_init_fit
      subroutine f2pywrap_lfitm1_line_shape (line_shapef2pywrap, x)
      use lfitm1, only : line_shape
      real(kind=8) x
      real(kind=8) line_shapef2pywrap
      line_shapef2pywrap = line_shape(x)
      end subroutine f2pywrap_lfitm1_line_shape
      subroutine f2pywrap_lfitm1_peak_fit (peak_fitf2pywrap, x, y, sig, &
     &ndata, f2py_x_d0, f2py_y_d0, f2py_sig_d0)
      use lfitm1, only : peak_fit
      integer ndata
      integer f2py_x_d0
      integer f2py_y_d0
      integer f2py_sig_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) y(f2py_y_d0)
      real(kind=8) sig(f2py_sig_d0)
      real(kind=8) peak_fitf2pywrap
      peak_fitf2pywrap = peak_fit(x, y, sig, ndata)
      end subroutine f2pywrap_lfitm1_peak_fit
      
      subroutine f2pyinitlfitm1(f2pysetupfunc)
      use lfitm1, only : ap
      use lfitm1, only : bp
      use lfitm1, only : x_0
      use lfitm1, only : y_0
      use lfitm1, only : norder
      use lfitm1, only : ma
      use lfitm1, only : ncvm
      use lfitm1, only : mfit
      use lfitm1, only : np
      use lfitm1, only : x_p
      use lfitm1, only : lista
      use lfitm1, only : ndata
      use lfitm1, only : mmax
      use lfitm1, only : a
      use lfitm1, only : covar
      use lfitm1, only : mat
      use lfitm1, only : matinv
      use lfitm1, only : beta
      use lfitm1, only : afunc
      use lfitm1, only : ipiv
      use lfitm1, only : indxr
      use lfitm1, only : indxc
      use lfitm1, only : set_par
      use lfitm1, only : free_all
      use lfitm1, only : calc_peak_shape
      use lfitm1, only : shapes
      use lfitm1, only : pfit
      use lfitm1, only : covsrt
      use lfitm1, only : gaussj
      interface 
      subroutine f2pywrap_lfitm1_init_all (al, bl, xp, n_peaks, n_order,&
     & vary_code, istat, f2py_xp_d0, f2py_vary_code_d0)
      real(kind=8) al
      real(kind=8) bl
      integer n_peaks
      integer n_order
      integer istat
      integer f2py_xp_d0
      integer f2py_vary_code_d0
      real(kind=8) xp(f2py_xp_d0)
      integer vary_code(f2py_vary_code_d0)
      end subroutine f2pywrap_lfitm1_init_all 
      subroutine f2pywrap_lfitm1_init_fit (vary_code, f2py_vary_code_d0)
      integer f2py_vary_code_d0
      integer vary_code(f2py_vary_code_d0)
      end subroutine f2pywrap_lfitm1_init_fit 
      subroutine f2pywrap_lfitm1_line_shape (line_shapef2pywrap, line_sh&
     &ape, x)
      real(kind=8) line_shape
      real(kind=8) x
      real(kind=8) line_shapef2pywrap
      end subroutine f2pywrap_lfitm1_line_shape 
      subroutine f2pywrap_lfitm1_peak_fit (peak_fitf2pywrap, peak_fit, x&
     &, y, sig, ndata, f2py_x_d0, f2py_y_d0, f2py_sig_d0)
      real(kind=8) peak_fit
      integer ndata
      integer f2py_x_d0
      integer f2py_y_d0
      integer f2py_sig_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) y(f2py_y_d0)
      real(kind=8) sig(f2py_sig_d0)
      real(kind=8) peak_fitf2pywrap
      end subroutine f2pywrap_lfitm1_peak_fit
      end interface
      external f2pysetupfunc
      external f2py_lfitm1_getdims_x_p
      external f2py_lfitm1_getdims_lista
      external f2py_lfitm1_getdims_a
      external f2py_lfitm1_getdims_covar
      external f2py_lfitm1_getdims_mat
      external f2py_lfitm1_getdims_matinv
      external f2py_lfitm1_getdims_beta
      external f2py_lfitm1_getdims_afunc
      external f2py_lfitm1_getdims_ipiv
      external f2py_lfitm1_getdims_indxr
      external f2py_lfitm1_getdims_indxc
      call f2pysetupfunc(ap,bp,x_0,y_0,norder,ma,ncvm,mfit,np,f2py_lfitm&
     &1_getdims_x_p,f2py_lfitm1_getdims_lista,ndata,mmax,f2py_lfitm1_get&
     &dims_a,f2py_lfitm1_getdims_covar,f2py_lfitm1_getdims_mat,f2py_lfit&
     &m1_getdims_matinv,f2py_lfitm1_getdims_beta,f2py_lfitm1_getdims_afu&
     &nc,f2py_lfitm1_getdims_ipiv,f2py_lfitm1_getdims_indxr,f2py_lfitm1_&
     &getdims_indxc,f2pywrap_lfitm1_init_all,set_par,free_all,f2pywrap_l&
     &fitm1_init_fit,calc_peak_shape,shapes,f2pywrap_lfitm1_line_shape,f&
     &2pywrap_lfitm1_peak_fit,pfit,covsrt,gaussj)
      end subroutine f2pyinitlfitm1


