C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.23.3)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapm33det (m33detf2pywrap, a)
      external m33det
      real(kind=8) a(3,3)
      real(kind=8) m33detf2pywrap, m33det
      m33detf2pywrap = m33det(a)
      end

