/* File: lfitm1module.c
 * This file is auto-generated with f2py (version:1.23.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Mar 22 12:01:11 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *lfitm1_error;
static PyObject *lfitm1_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(lfitm1_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = lfitm1_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = lfitm1_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** init_all **********************************/
static char doc_f2py_rout_lfitm1_lfitm1_init_all[] = "\
istat = init_all(al,bl,xp,n_peaks,n_order,vary_code)\n\nWrapper for ``init_all``.\
\n\nParameters\n----------\n"
"al : input float\n"
"bl : input float\n"
"xp : input rank-1 array('d') with bounds (f2py_xp_d0)\n"
"n_peaks : input int\n"
"n_order : input int\n"
"vary_code : input rank-1 array('i') with bounds (f2py_vary_code_d0)\n"
"\nReturns\n-------\n"
"istat : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_lfitm1_lfitm1_init_all(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double al = 0;
    PyObject *al_capi = Py_None;
    double bl = 0;
    PyObject *bl_capi = Py_None;
    double *xp = NULL;
    npy_intp xp_Dims[1] = {-1};
    const int xp_Rank = 1;
    PyArrayObject *capi_xp_tmp = NULL;
    int capi_xp_intent = 0;
    PyObject *xp_capi = Py_None;
    int n_peaks = 0;
    PyObject *n_peaks_capi = Py_None;
    int n_order = 0;
    PyObject *n_order_capi = Py_None;
    int *vary_code = NULL;
    npy_intp vary_code_Dims[1] = {-1};
    const int vary_code_Rank = 1;
    PyArrayObject *capi_vary_code_tmp = NULL;
    int capi_vary_code_intent = 0;
    PyObject *vary_code_capi = Py_None;
    int istat = 0;
    int f2py_xp_d0 = 0;
    int f2py_vary_code_d0 = 0;
    static char *capi_kwlist[] = {"al","bl","xp","n_peaks","n_order","vary_code",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOO|:lfitm1.lfitm1.init_all",\
        capi_kwlist,&al_capi,&bl_capi,&xp_capi,&n_peaks_capi,&n_order_capi,&vary_code_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable al */
        f2py_success = double_from_pyobj(&al,al_capi,"lfitm1.lfitm1.init_all() 1st argument (al) can't be converted to double");
    if (f2py_success) {
    /* Processing variable bl */
        f2py_success = double_from_pyobj(&bl,bl_capi,"lfitm1.lfitm1.init_all() 2nd argument (bl) can't be converted to double");
    if (f2py_success) {
    /* Processing variable xp */
    ;
    capi_xp_intent |= F2PY_INTENT_IN;
    capi_xp_tmp = array_from_pyobj(NPY_DOUBLE,xp_Dims,xp_Rank,capi_xp_intent,xp_capi);
    if (capi_xp_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 3rd argument `xp' of lfitm1.lfitm1.init_all to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xp = (double *)(PyArray_DATA(capi_xp_tmp));

    /* Processing variable n_peaks */
        f2py_success = int_from_pyobj(&n_peaks,n_peaks_capi,"lfitm1.lfitm1.init_all() 4th argument (n_peaks) can't be converted to int");
    if (f2py_success) {
    /* Processing variable n_order */
        f2py_success = int_from_pyobj(&n_order,n_order_capi,"lfitm1.lfitm1.init_all() 5th argument (n_order) can't be converted to int");
    if (f2py_success) {
    /* Processing variable vary_code */
    ;
    capi_vary_code_intent |= F2PY_INTENT_IN;
    capi_vary_code_tmp = array_from_pyobj(NPY_INT,vary_code_Dims,vary_code_Rank,capi_vary_code_intent,vary_code_capi);
    if (capi_vary_code_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 6th argument `vary_code' of lfitm1.lfitm1.init_all to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        vary_code = (int *)(PyArray_DATA(capi_vary_code_tmp));

    /* Processing variable istat */
    /* Processing variable f2py_xp_d0 */
    f2py_xp_d0 = shape(xp, 0);
    /* Processing variable f2py_vary_code_d0 */
    f2py_vary_code_d0 = shape(vary_code, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&al,&bl,xp,&n_peaks,&n_order,vary_code,&istat,&f2py_xp_d0,&f2py_vary_code_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",istat);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vary_code_d0 */
    /* End of cleaning variable f2py_xp_d0 */
    /* End of cleaning variable istat */
    if((PyObject *)capi_vary_code_tmp!=vary_code_capi) {
        Py_XDECREF(capi_vary_code_tmp); }
    }  /*if (capi_vary_code_tmp == NULL) ... else of vary_code*/
    /* End of cleaning variable vary_code */
    } /*if (f2py_success) of n_order*/
    /* End of cleaning variable n_order */
    } /*if (f2py_success) of n_peaks*/
    /* End of cleaning variable n_peaks */
    if((PyObject *)capi_xp_tmp!=xp_capi) {
        Py_XDECREF(capi_xp_tmp); }
    }  /*if (capi_xp_tmp == NULL) ... else of xp*/
    /* End of cleaning variable xp */
    } /*if (f2py_success) of bl*/
    /* End of cleaning variable bl */
    } /*if (f2py_success) of al*/
    /* End of cleaning variable al */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of init_all ******************************/

/********************************** set_par **********************************/
static char doc_f2py_rout_lfitm1_lfitm1_set_par[] = "\
set_par(i,x)\n\nWrapper for ``set_par``.\
\n\nParameters\n----------\n"
"i : input int\n"
"x : input float";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_set_par(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int i = 0;
    PyObject *i_capi = Py_None;
    double x = 0;
    PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"i","x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:lfitm1.lfitm1.set_par",\
        capi_kwlist,&i_capi,&x_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable i */
        f2py_success = int_from_pyobj(&i,i_capi,"lfitm1.lfitm1.set_par() 1st argument (i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable x */
        f2py_success = double_from_pyobj(&x,x_capi,"lfitm1.lfitm1.set_par() 2nd argument (x) can't be converted to double");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&i,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of x*/
    /* End of cleaning variable x */
    } /*if (f2py_success) of i*/
    /* End of cleaning variable i */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of set_par *******************************/

/********************************** free_all **********************************/
static char doc_f2py_rout_lfitm1_lfitm1_free_all[] = "\
free_all()\n\nWrapper for ``free_all``.\
\n";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_free_all(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:lfitm1.lfitm1.free_all",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of free_all ******************************/

/********************************** init_fit **********************************/
static char doc_f2py_rout_lfitm1_lfitm1_init_fit[] = "\
init_fit(vary_code)\n\nWrapper for ``init_fit``.\
\n\nParameters\n----------\n"
"vary_code : input rank-1 array('i') with bounds (f2py_vary_code_d0)";
/* #declfortranroutine# */
static PyObject *f2py_rout_lfitm1_lfitm1_init_fit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *vary_code = NULL;
    npy_intp vary_code_Dims[1] = {-1};
    const int vary_code_Rank = 1;
    PyArrayObject *capi_vary_code_tmp = NULL;
    int capi_vary_code_intent = 0;
    PyObject *vary_code_capi = Py_None;
    int f2py_vary_code_d0 = 0;
    static char *capi_kwlist[] = {"vary_code",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:lfitm1.lfitm1.init_fit",\
        capi_kwlist,&vary_code_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable vary_code */
    ;
    capi_vary_code_intent |= F2PY_INTENT_IN;
    capi_vary_code_tmp = array_from_pyobj(NPY_INT,vary_code_Dims,vary_code_Rank,capi_vary_code_intent,vary_code_capi);
    if (capi_vary_code_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 1st argument `vary_code' of lfitm1.lfitm1.init_fit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        vary_code = (int *)(PyArray_DATA(capi_vary_code_tmp));

    /* Processing variable f2py_vary_code_d0 */
    f2py_vary_code_d0 = shape(vary_code, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(vary_code,&f2py_vary_code_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_vary_code_d0 */
    if((PyObject *)capi_vary_code_tmp!=vary_code_capi) {
        Py_XDECREF(capi_vary_code_tmp); }
    }  /*if (capi_vary_code_tmp == NULL) ... else of vary_code*/
    /* End of cleaning variable vary_code */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of init_fit ******************************/

/****************************** calc_peak_shape ******************************/
static char doc_f2py_rout_lfitm1_lfitm1_calc_peak_shape[] = "\
calc_peak_shape(al,bl)\n\nWrapper for ``calc_peak_shape``.\
\n\nParameters\n----------\n"
"al : input float\n"
"bl : input float";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_calc_peak_shape(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double al = 0;
    PyObject *al_capi = Py_None;
    double bl = 0;
    PyObject *bl_capi = Py_None;
    static char *capi_kwlist[] = {"al","bl",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:lfitm1.lfitm1.calc_peak_shape",\
        capi_kwlist,&al_capi,&bl_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable al */
        f2py_success = double_from_pyobj(&al,al_capi,"lfitm1.lfitm1.calc_peak_shape() 1st argument (al) can't be converted to double");
    if (f2py_success) {
    /* Processing variable bl */
        f2py_success = double_from_pyobj(&bl,bl_capi,"lfitm1.lfitm1.calc_peak_shape() 2nd argument (bl) can't be converted to double");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&al,&bl);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of bl*/
    /* End of cleaning variable bl */
    } /*if (f2py_success) of al*/
    /* End of cleaning variable al */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of calc_peak_shape ***************************/

/*********************************** shapes ***********************************/
static char doc_f2py_rout_lfitm1_lfitm1_shapes[] = "\
shapes(x)\n\nWrapper for ``shapes``.\
\n\nParameters\n----------\n"
"x : input float";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_shapes(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double x = 0;
    PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:lfitm1.lfitm1.shapes",\
        capi_kwlist,&x_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
        f2py_success = double_from_pyobj(&x,x_capi,"lfitm1.lfitm1.shapes() 1st argument (x) can't be converted to double");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of x*/
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of shapes *******************************/

/********************************* line_shape *********************************/
static char doc_f2py_rout_lfitm1_lfitm1_line_shape[] = "\
line_shape = line_shape(x)\n\nWrapper for ``line_shape``.\
\n\nParameters\n----------\n"
"x : input float\n"
"\nReturns\n-------\n"
"line_shape : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_lfitm1_lfitm1_line_shape(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double line_shape = 0;
    double x = 0;
    PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:lfitm1.lfitm1.line_shape",\
        capi_kwlist,&x_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
        f2py_success = double_from_pyobj(&x,x_capi,"lfitm1.lfitm1.line_shape() 1st argument (x) can't be converted to double");
    if (f2py_success) {
    /* Processing variable line_shape */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&line_shape,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",line_shape);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable line_shape */
    } /*if (f2py_success) of x*/
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of line_shape *****************************/

/********************************** peak_fit **********************************/
static char doc_f2py_rout_lfitm1_lfitm1_peak_fit[] = "\
peak_fit = peak_fit(x,y,sig,ndata)\n\nWrapper for ``peak_fit``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"y : input rank-1 array('d') with bounds (f2py_y_d0)\n"
"sig : input rank-1 array('d') with bounds (f2py_sig_d0)\n"
"ndata : input int\n"
"\nReturns\n-------\n"
"peak_fit : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_lfitm1_lfitm1_peak_fit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double peak_fit = 0;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_tmp = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_tmp = NULL;
    int capi_y_intent = 0;
    PyObject *y_capi = Py_None;
    double *sig = NULL;
    npy_intp sig_Dims[1] = {-1};
    const int sig_Rank = 1;
    PyArrayObject *capi_sig_tmp = NULL;
    int capi_sig_intent = 0;
    PyObject *sig_capi = Py_None;
    int ndata = 0;
    PyObject *ndata_capi = Py_None;
    int f2py_x_d0 = 0;
    int f2py_y_d0 = 0;
    int f2py_sig_d0 = 0;
    static char *capi_kwlist[] = {"x","y","sig","ndata",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:lfitm1.lfitm1.peak_fit",\
        capi_kwlist,&x_capi,&y_capi,&sig_capi,&ndata_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
    if (capi_x_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 1st argument `x' of lfitm1.lfitm1.peak_fit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x = (double *)(PyArray_DATA(capi_x_tmp));

    /* Processing variable y */
    ;
    capi_y_intent |= F2PY_INTENT_IN;
    capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
    if (capi_y_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 2nd argument `y' of lfitm1.lfitm1.peak_fit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        y = (double *)(PyArray_DATA(capi_y_tmp));

    /* Processing variable sig */
    ;
    capi_sig_intent |= F2PY_INTENT_IN;
    capi_sig_tmp = array_from_pyobj(NPY_DOUBLE,sig_Dims,sig_Rank,capi_sig_intent,sig_capi);
    if (capi_sig_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 3rd argument `sig' of lfitm1.lfitm1.peak_fit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sig = (double *)(PyArray_DATA(capi_sig_tmp));

    /* Processing variable ndata */
        f2py_success = int_from_pyobj(&ndata,ndata_capi,"lfitm1.lfitm1.peak_fit() 4th argument (ndata) can't be converted to int");
    if (f2py_success) {
    /* Processing variable peak_fit */
    /* Processing variable f2py_x_d0 */
    f2py_x_d0 = shape(x, 0);
    /* Processing variable f2py_y_d0 */
    f2py_y_d0 = shape(y, 0);
    /* Processing variable f2py_sig_d0 */
    f2py_sig_d0 = shape(sig, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&peak_fit,x,y,sig,&ndata,&f2py_x_d0,&f2py_y_d0,&f2py_sig_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",peak_fit);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_sig_d0 */
    /* End of cleaning variable f2py_y_d0 */
    /* End of cleaning variable f2py_x_d0 */
    /* End of cleaning variable peak_fit */
    } /*if (f2py_success) of ndata*/
    /* End of cleaning variable ndata */
    if((PyObject *)capi_sig_tmp!=sig_capi) {
        Py_XDECREF(capi_sig_tmp); }
    }  /*if (capi_sig_tmp == NULL) ... else of sig*/
    /* End of cleaning variable sig */
    if((PyObject *)capi_y_tmp!=y_capi) {
        Py_XDECREF(capi_y_tmp); }
    }  /*if (capi_y_tmp == NULL) ... else of y*/
    /* End of cleaning variable y */
    if((PyObject *)capi_x_tmp!=x_capi) {
        Py_XDECREF(capi_x_tmp); }
    }  /*if (capi_x_tmp == NULL) ... else of x*/
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of peak_fit ******************************/

/************************************ pfit ************************************/
static char doc_f2py_rout_lfitm1_lfitm1_pfit[] = "\
chi_sq = pfit(x,y,sig,[ndata])\n\nWrapper for ``pfit``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (ndata)\n"
"y : input rank-1 array('d') with bounds (ndata)\n"
"sig : input rank-1 array('d') with bounds (ndata)\n"
"\nOther Parameters\n----------------\n"
"ndata : input int, optional\n    Default: shape(x, 0)\n"
"\nReturns\n-------\n"
"chi_sq : float";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_pfit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_tmp = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_tmp = NULL;
    int capi_y_intent = 0;
    PyObject *y_capi = Py_None;
    double *sig = NULL;
    npy_intp sig_Dims[1] = {-1};
    const int sig_Rank = 1;
    PyArrayObject *capi_sig_tmp = NULL;
    int capi_sig_intent = 0;
    PyObject *sig_capi = Py_None;
    int ndata = 0;
    PyObject *ndata_capi = Py_None;
    double chi_sq = 0;
    static char *capi_kwlist[] = {"x","y","sig","ndata",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:lfitm1.lfitm1.pfit",\
        capi_kwlist,&x_capi,&y_capi,&sig_capi,&ndata_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
    if (capi_x_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 1st argument `x' of lfitm1.lfitm1.pfit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x = (double *)(PyArray_DATA(capi_x_tmp));

    /* Processing variable chi_sq */
    /* Processing variable ndata */
    if (ndata_capi == Py_None) ndata = shape(x, 0); else
        f2py_success = int_from_pyobj(&ndata,ndata_capi,"lfitm1.lfitm1.pfit() 1st keyword (ndata) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(x, 0) == ndata,"shape(x, 0) == ndata","1st keyword ndata","pfit:ndata=%d",ndata) {
    /* Processing variable y */
    y_Dims[0]=ndata;
    capi_y_intent |= F2PY_INTENT_IN;
    capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
    if (capi_y_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 2nd argument `y' of lfitm1.lfitm1.pfit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        y = (double *)(PyArray_DATA(capi_y_tmp));

    /* Processing variable sig */
    sig_Dims[0]=ndata;
    capi_sig_intent |= F2PY_INTENT_IN;
    capi_sig_tmp = array_from_pyobj(NPY_DOUBLE,sig_Dims,sig_Rank,capi_sig_intent,sig_capi);
    if (capi_sig_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 3rd argument `sig' of lfitm1.lfitm1.pfit to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sig = (double *)(PyArray_DATA(capi_sig_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(x,y,sig,&ndata,&chi_sq);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",chi_sq);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_sig_tmp!=sig_capi) {
        Py_XDECREF(capi_sig_tmp); }
    }  /*if (capi_sig_tmp == NULL) ... else of sig*/
    /* End of cleaning variable sig */
    if((PyObject *)capi_y_tmp!=y_capi) {
        Py_XDECREF(capi_y_tmp); }
    }  /*if (capi_y_tmp == NULL) ... else of y*/
    /* End of cleaning variable y */
    } /*CHECKSCALAR(shape(x, 0) == ndata)*/
    } /*if (f2py_success) of ndata*/
    /* End of cleaning variable ndata */
    /* End of cleaning variable chi_sq */
    if((PyObject *)capi_x_tmp!=x_capi) {
        Py_XDECREF(capi_x_tmp); }
    }  /*if (capi_x_tmp == NULL) ... else of x*/
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of pfit ********************************/

/*********************************** covsrt ***********************************/
static char doc_f2py_rout_lfitm1_lfitm1_covsrt[] = "\
covsrt()\n\nWrapper for ``covsrt``.\
\n";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_covsrt(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:lfitm1.lfitm1.covsrt",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of covsrt *******************************/

/*********************************** gaussj ***********************************/
static char doc_f2py_rout_lfitm1_lfitm1_gaussj[] = "\
gaussj(a,n,b,m,err,[np,mp])\n\nWrapper for ``gaussj``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (np,np)\n"
"n : input int\n"
"b : input rank-2 array('d') with bounds (np,mp)\n"
"m : input int\n"
"err : input int\n"
"\nOther Parameters\n----------------\n"
"np : input int, optional\n    Default: shape(a, 0)\n"
"mp : input int, optional\n    Default: shape(b, 1)";
/*  */
static PyObject *f2py_rout_lfitm1_lfitm1_gaussj(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_tmp = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    int np = 0;
    PyObject *np_capi = Py_None;
    double *b = NULL;
    npy_intp b_Dims[2] = {-1, -1};
    const int b_Rank = 2;
    PyArrayObject *capi_b_tmp = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    int m = 0;
    PyObject *m_capi = Py_None;
    int mp = 0;
    PyObject *mp_capi = Py_None;
    int err = 0;
    PyObject *err_capi = Py_None;
    static char *capi_kwlist[] = {"a","n","b","m","err","np","mp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|OO:lfitm1.lfitm1.gaussj",\
        capi_kwlist,&a_capi,&n_capi,&b_capi,&m_capi,&err_capi,&np_capi,&mp_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN;
    capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
    if (capi_a_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 1st argument `a' of lfitm1.lfitm1.gaussj to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        a = (double *)(PyArray_DATA(capi_a_tmp));

    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"lfitm1.lfitm1.gaussj() 2nd argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable m */
        f2py_success = int_from_pyobj(&m,m_capi,"lfitm1.lfitm1.gaussj() 4th argument (m) can't be converted to int");
    if (f2py_success) {
    /* Processing variable err */
        f2py_success = int_from_pyobj(&err,err_capi,"lfitm1.lfitm1.gaussj() 5th argument (err) can't be converted to int");
    if (f2py_success) {
    /* Processing variable np */
    if (np_capi == Py_None) np = shape(a, 0); else
        f2py_success = int_from_pyobj(&np,np_capi,"lfitm1.lfitm1.gaussj() 1st keyword (np) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(a, 0) == np,"shape(a, 0) == np","1st keyword np","gaussj:np=%d",np) {
    /* Processing variable b */
    b_Dims[0]=np;
    capi_b_intent |= F2PY_INTENT_IN;
    capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
    if (capi_b_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : lfitm1_error,"failed in converting 3rd argument `b' of lfitm1.lfitm1.gaussj to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        b = (double *)(PyArray_DATA(capi_b_tmp));

    /* Processing variable mp */
    if (mp_capi == Py_None) mp = shape(b, 1); else
        f2py_success = int_from_pyobj(&mp,mp_capi,"lfitm1.lfitm1.gaussj() 2nd keyword (mp) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(b, 1) == mp,"shape(b, 1) == mp","2nd keyword mp","gaussj:mp=%d",mp) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(a,&n,&np,b,&m,&mp,&err);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(b, 1) == mp)*/
    } /*if (f2py_success) of mp*/
    /* End of cleaning variable mp */
    if((PyObject *)capi_b_tmp!=b_capi) {
        Py_XDECREF(capi_b_tmp); }
    }  /*if (capi_b_tmp == NULL) ... else of b*/
    /* End of cleaning variable b */
    } /*CHECKSCALAR(shape(a, 0) == np)*/
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
    } /*if (f2py_success) of err*/
    /* End of cleaning variable err */
    } /*if (f2py_success) of m*/
    /* End of cleaning variable m */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_a_tmp!=a_capi) {
        Py_XDECREF(capi_a_tmp); }
    }  /*if (capi_a_tmp == NULL) ... else of a*/
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of gaussj *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_lfitm1_def[] = {
  {"ap",0,{{-1}},NPY_DOUBLE},
  {"bp",0,{{-1}},NPY_DOUBLE},
  {"x_0",0,{{-1}},NPY_DOUBLE},
  {"y_0",0,{{-1}},NPY_DOUBLE},
  {"norder",0,{{-1}},NPY_INT},
  {"ma",0,{{-1}},NPY_INT},
  {"ncvm",0,{{-1}},NPY_INT},
  {"mfit",0,{{-1}},NPY_INT},
  {"np",0,{{-1}},NPY_INT},
  {"x_p",1,{{-1}},NPY_DOUBLE},
  {"lista",1,{{-1}},NPY_INT},
  {"ndata",0,{{-1}},NPY_INT},
  {"mmax",0,{{-1}},NPY_INT},
  {"a",1,{{-1}},NPY_DOUBLE},
  {"covar",2,{{-1,-1}},NPY_DOUBLE},
  {"mat",2,{{-1,-1}},NPY_DOUBLE},
  {"matinv",2,{{-1,-1}},NPY_DOUBLE},
  {"beta",1,{{-1}},NPY_DOUBLE},
  {"afunc",1,{{-1}},NPY_DOUBLE},
  {"ipiv",1,{{-1}},NPY_INT},
  {"indxr",1,{{-1}},NPY_INT},
  {"indxc",1,{{-1}},NPY_INT},
  {"init_all",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_init_all,doc_f2py_rout_lfitm1_lfitm1_init_all},
  {"set_par",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_set_par,doc_f2py_rout_lfitm1_lfitm1_set_par},
  {"free_all",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_free_all,doc_f2py_rout_lfitm1_lfitm1_free_all},
  {"init_fit",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_init_fit,doc_f2py_rout_lfitm1_lfitm1_init_fit},
  {"calc_peak_shape",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_calc_peak_shape,doc_f2py_rout_lfitm1_lfitm1_calc_peak_shape},
  {"shapes",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_shapes,doc_f2py_rout_lfitm1_lfitm1_shapes},
  {"line_shape",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_line_shape,doc_f2py_rout_lfitm1_lfitm1_line_shape},
  {"peak_fit",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_peak_fit,doc_f2py_rout_lfitm1_lfitm1_peak_fit},
  {"pfit",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_pfit,doc_f2py_rout_lfitm1_lfitm1_pfit},
  {"covsrt",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_covsrt,doc_f2py_rout_lfitm1_lfitm1_covsrt},
  {"gaussj",-1,{{-1}},0,NULL,(void *)f2py_rout_lfitm1_lfitm1_gaussj,doc_f2py_rout_lfitm1_lfitm1_gaussj},
  {NULL}
};

static void f2py_setup_lfitm1(char *ap,char *bp,char *x_0,char *y_0,char *norder,char *ma,char *ncvm,char *mfit,char *np,void (*x_p)(int*,int*,void(*)(char*,int*),int*),void (*lista)(int*,int*,void(*)(char*,int*),int*),char *ndata,char *mmax,void (*a)(int*,int*,void(*)(char*,int*),int*),void (*covar)(int*,int*,void(*)(char*,int*),int*),void (*mat)(int*,int*,void(*)(char*,int*),int*),void (*matinv)(int*,int*,void(*)(char*,int*),int*),void (*beta)(int*,int*,void(*)(char*,int*),int*),void (*afunc)(int*,int*,void(*)(char*,int*),int*),void (*ipiv)(int*,int*,void(*)(char*,int*),int*),void (*indxr)(int*,int*,void(*)(char*,int*),int*),void (*indxc)(int*,int*,void(*)(char*,int*),int*),char *init_all,char *set_par,char *free_all,char *init_fit,char *calc_peak_shape,char *shapes,char *line_shape,char *peak_fit,char *pfit,char *covsrt,char *gaussj) {
  int i_f2py=0;
  f2py_lfitm1_def[i_f2py++].data = ap;
  f2py_lfitm1_def[i_f2py++].data = bp;
  f2py_lfitm1_def[i_f2py++].data = x_0;
  f2py_lfitm1_def[i_f2py++].data = y_0;
  f2py_lfitm1_def[i_f2py++].data = norder;
  f2py_lfitm1_def[i_f2py++].data = ma;
  f2py_lfitm1_def[i_f2py++].data = ncvm;
  f2py_lfitm1_def[i_f2py++].data = mfit;
  f2py_lfitm1_def[i_f2py++].data = np;
  f2py_lfitm1_def[i_f2py++].func = x_p;
  f2py_lfitm1_def[i_f2py++].func = lista;
  f2py_lfitm1_def[i_f2py++].data = ndata;
  f2py_lfitm1_def[i_f2py++].data = mmax;
  f2py_lfitm1_def[i_f2py++].func = a;
  f2py_lfitm1_def[i_f2py++].func = covar;
  f2py_lfitm1_def[i_f2py++].func = mat;
  f2py_lfitm1_def[i_f2py++].func = matinv;
  f2py_lfitm1_def[i_f2py++].func = beta;
  f2py_lfitm1_def[i_f2py++].func = afunc;
  f2py_lfitm1_def[i_f2py++].func = ipiv;
  f2py_lfitm1_def[i_f2py++].func = indxr;
  f2py_lfitm1_def[i_f2py++].func = indxc;
  f2py_lfitm1_def[i_f2py++].data = init_all;
  f2py_lfitm1_def[i_f2py++].data = set_par;
  f2py_lfitm1_def[i_f2py++].data = free_all;
  f2py_lfitm1_def[i_f2py++].data = init_fit;
  f2py_lfitm1_def[i_f2py++].data = calc_peak_shape;
  f2py_lfitm1_def[i_f2py++].data = shapes;
  f2py_lfitm1_def[i_f2py++].data = line_shape;
  f2py_lfitm1_def[i_f2py++].data = peak_fit;
  f2py_lfitm1_def[i_f2py++].data = pfit;
  f2py_lfitm1_def[i_f2py++].data = covsrt;
  f2py_lfitm1_def[i_f2py++].data = gaussj;
}
extern void F_FUNC(f2pyinitlfitm1,F2PYINITLFITM1)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char*,char*,void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_lfitm1(void) {
  F_FUNC(f2pyinitlfitm1,F2PYINITLFITM1)(f2py_setup_lfitm1);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "lfitm1",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_lfitm1(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = lfitm1_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module lfitm1 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'lfitm1' is auto-generated with f2py (version:1.23.3).\nFunctions:\n"
"Fortran 90/95 modules:\n""  lfitm1 --- ap,bp,x_0,y_0,norder,ma,ncvm,mfit,np,x_p,lista,ndata,mmax,a,covar,mat,matinv,beta,afunc,ipiv,indxr,indxc,init_all(),set_par(),free_all(),init_fit(),calc_peak_shape(),shapes(),line_shape(),peak_fit(),pfit(),covsrt(),gaussj()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    lfitm1_error = PyErr_NewException ("lfitm1.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_lfitm1_error", lfitm1_error);
    Py_DECREF(lfitm1_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }











/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "lfitm1", PyFortranObject_New(f2py_lfitm1_def,f2py_init_lfitm1));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"lfitm1");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
