!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.3.0)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapprint_real_array (x, name, f2py_x_d0)
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      character*(*) name
      interface
      
            subroutine print_real_array(x,name) 
                real(kind=8), dimension(:),intent(in) :: x
                character*(*), intent(in) :: name
            end subroutine print_real_array
      end interface
      call print_real_array(x, name)
      end


      subroutine f2pywrapprint_real_matrix (m, name, f2py_m_d0, f2py_m_d&
     &1)
      integer f2py_m_d0
      integer f2py_m_d1
      real(kind=8) m(f2py_m_d0,f2py_m_d1)
      character*(*) name
      interface
      
            subroutine print_real_matrix(m,name) 
                real(kind=8), dimension(:,:),intent(in) :: m
                character*(*), intent(in) :: name
            end subroutine print_real_matrix
      end interface
      call print_real_matrix(m, name)
      end


      subroutine f2pywrapfit_parabola (fit_parabolaf2pywrap, x, y, f2py_&
     &x_d0, f2py_y_d0)
      integer f2py_x_d0
      integer f2py_y_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) y(f2py_y_d0)
      real(kind=8) fit_parabolaf2pywrap(3)
      interface
      function fit_parabola(x,y) result (a) 
          real(kind=8), dimension(:),intent(in) :: x
          real(kind=8), dimension(:),intent(in) :: y
          real(kind=8), dimension(3) :: a
      end function fit_parabola
      end interface
      fit_parabolaf2pywrap = fit_parabola(x, y)
      end

