/* File: ffind_peaks2module.c
 * This file is auto-generated with f2py (version:2.3.0).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Dec  3 14:21:42 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *ffind_peaks2_error;
static PyObject *ffind_peaks2_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)


#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(len+1)) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(ffind_peaks2_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)


/*
STRINGPADN replaces null values with padding values from the right.

`to` must have size of at least N bytes.

If the `to[N-1]` has null value, then replace it and all the
preceding, nulls with the given padding.

STRINGPADN(to, N, PADDING, NULLVALUE) is an inverse operation.
*/
#define STRINGPADN(to, N, NULLVALUE, PADDING)                   \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        for (_m -= 1; _m >= 0 && _to[_m] == NULLVALUE; _m--) {  \
             _to[_m] = PADDING;                                 \
        }                                                       \
    } while (0)


/*
STRINGCOPYN copies N bytes.

`to` and `from` buffers must have sizes of at least N bytes.
*/
#define STRINGCOPYN(to,from,N)                                  \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, _m);             \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = ffind_peaks2_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = ffind_peaks2_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/*
  Create a new string buffer `str` of at most length `len` from a
  Python string-like object `obj`.

  The string buffer has given size (len) or the size of inistr when len==-1.

  The string buffer is padded with blanks: in Fortran, trailing blanks
  are insignificant contrary to C nulls.
 */
static int
string_from_pyobj(string *str, int *len, const string inistr, PyObject *obj,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    string buf = NULL;
    npy_intp n = -1;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",
               (char*)str, *len, (char *)inistr, obj);
#endif
    if (obj == Py_None) {
        n = strlen(inistr);
        buf = inistr;
    }
    else if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,
                            "array object is non-contiguous.");
            goto capi_fail;
        }
        n = PyArray_NBYTES(arr);
        buf = PyArray_DATA(arr);
        n = strnlen(buf, n);
    }
    else {
        if (PyBytes_Check(obj)) {
            tmp = obj;
            Py_INCREF(tmp);
        }
        else if (PyUnicode_Check(obj)) {
            tmp = PyUnicode_AsASCIIString(obj);
        }
        else {
            PyObject *tmp2;
            tmp2 = PyObject_Str(obj);
            if (tmp2) {
                tmp = PyUnicode_AsASCIIString(tmp2);
                Py_DECREF(tmp2);
            }
            else {
                tmp = NULL;
            }
        }
        if (tmp == NULL) goto capi_fail;
        n = PyBytes_GET_SIZE(tmp);
        buf = PyBytes_AS_STRING(tmp);
    }
    if (*len == -1) {
        /* TODO: change the type of `len` so that we can remove this */
        if (n > NPY_MAX_INT) {
            PyErr_SetString(PyExc_OverflowError,
                            "object too large for a 32-bit int");
            goto capi_fail;
        }
        *len = n;
    }
    else if (*len < n) {
        /* discard the last (len-n) bytes of input buf */
        n = *len;
    }
    if (n < 0 || *len < 0 || buf == NULL) {
        goto capi_fail;
    }
    STRINGMALLOC(*str, *len);  // *str is allocated with size (*len + 1)
    if (n < *len) {
        /*
          Pad fixed-width string with nulls. The caller will replace
          nulls with blanks when the corresponding argument is not
          intent(c).
        */
        memset(*str + n, '\0', *len - n);
    }
    STRINGCOPYN(*str, buf, n);
    Py_XDECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = ffind_peaks2_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(find_peaks,FIND_PEAKS)(int*,int*,double*,double*,int*,int*,int*,int*);
extern void F_WRAPPEDFUNC(m33det,M33DET)(double*,double*);
extern void F_WRAPPEDFUNC_US(print_real_array,PRINT_REAL_ARRAY)(double*,string,int*,size_t);
extern void F_WRAPPEDFUNC_US(print_real_matrix,PRINT_REAL_MATRIX)(double*,string,int*,int*,size_t);
extern void F_WRAPPEDFUNC_US(fit_parabola,FIT_PARABOLA)(double*,double*,double*,int*,int*);
extern void F_FUNC_US(refine_positions,REFINE_POSITIONS)(int*,int*,int*,int*,double*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* find_peaks *********************************/
static char doc_f2py_rout_ffind_peaks2_find_peaks[] = "\
n_min,min_pos,n_max,max_pos = find_peaks(np,delta,val,[n])\n\nWrapper for ``find_peaks``.\
\n\nParameters\n----------\n"
"np : input int\n"
"delta : input float\n"
"val : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(val, 0)\n"
"\nReturns\n-------\n"
"n_min : int\n"
"min_pos : rank-1 array('i') with bounds (np)\n"
"n_max : int\n"
"max_pos : rank-1 array('i') with bounds (np)";
/* extern void F_FUNC_US(find_peaks,FIND_PEAKS)(int*,int*,double*,double*,int*,int*,int*,int*); */
static PyObject *f2py_rout_ffind_peaks2_find_peaks(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    int np = 0;
    PyObject *np_capi = Py_None;
    double delta = 0;
    PyObject *delta_capi = Py_None;
    double *val = NULL;
    npy_intp val_Dims[1] = {-1};
    const int val_Rank = 1;
    PyArrayObject *capi_val_as_array = NULL;
    int capi_val_intent = 0;
    PyObject *val_capi = Py_None;
    int n_min = 0;
    int *min_pos = NULL;
    npy_intp min_pos_Dims[1] = {-1};
    const int min_pos_Rank = 1;
    PyArrayObject *capi_min_pos_as_array = NULL;
    int capi_min_pos_intent = 0;
    int n_max = 0;
    int *max_pos = NULL;
    npy_intp max_pos_Dims[1] = {-1};
    const int max_pos_Rank = 1;
    PyArrayObject *capi_max_pos_as_array = NULL;
    int capi_max_pos_intent = 0;
    static char *capi_kwlist[] = {"np","delta","val","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:ffind_peaks2.find_peaks",\
        capi_kwlist,&np_capi,&delta_capi,&val_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable np */
        f2py_success = int_from_pyobj(&np,np_capi,"ffind_peaks2.find_peaks() 1st argument (np) can't be converted to int");
    if (f2py_success) {
    /* Processing variable delta */
        f2py_success = double_from_pyobj(&delta,delta_capi,"ffind_peaks2.find_peaks() 2nd argument (delta) can't be converted to double");
    if (f2py_success) {
    /* Processing variable val */
    ;
    capi_val_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.find_peaks: failed to create array from the 3rd argument `val`";
    capi_val_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,val_Dims,val_Rank,  capi_val_intent,val_capi,capi_errmess);
    if (capi_val_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        val = (double *)(PyArray_DATA(capi_val_as_array));

    /* Processing variable n_min */
    /* Processing variable n_max */
    /* Processing variable n */
    if (n_capi == Py_None) n = shape(val, 0); else
        f2py_success = int_from_pyobj(&n,n_capi,"ffind_peaks2.find_peaks() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(val, 0) == n,"shape(val, 0) == n","1st keyword n","find_peaks:n=%d",n) {
    /* Processing variable min_pos */
    min_pos_Dims[0]=np;
    capi_min_pos_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.find_peaks: failed to create array from the hidden `min_pos`";
    capi_min_pos_as_array = ndarray_from_pyobj(  NPY_INT,1,min_pos_Dims,min_pos_Rank,  capi_min_pos_intent,Py_None,capi_errmess);
    if (capi_min_pos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        min_pos = (int *)(PyArray_DATA(capi_min_pos_as_array));

    /* Processing variable max_pos */
    max_pos_Dims[0]=np;
    capi_max_pos_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.find_peaks: failed to create array from the hidden `max_pos`";
    capi_max_pos_as_array = ndarray_from_pyobj(  NPY_INT,1,max_pos_Dims,max_pos_Rank,  capi_max_pos_intent,Py_None,capi_errmess);
    if (capi_max_pos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        max_pos = (int *)(PyArray_DATA(capi_max_pos_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n,&np,&delta,val,&n_min,min_pos,&n_max,max_pos);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iNiN",n_min,capi_min_pos_as_array,n_max,capi_max_pos_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_max_pos_as_array == NULL) ... else of max_pos */
    /* End of cleaning variable max_pos */
    }  /* if (capi_min_pos_as_array == NULL) ... else of min_pos */
    /* End of cleaning variable min_pos */
    } /*CHECKSCALAR(shape(val, 0) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    /* End of cleaning variable n_max */
    /* End of cleaning variable n_min */
    if((PyObject *)capi_val_as_array!=val_capi) {
        Py_XDECREF(capi_val_as_array); }
    }  /* if (capi_val_as_array == NULL) ... else of val */
    /* End of cleaning variable val */
    } /*if (f2py_success) of delta*/
    /* End of cleaning variable delta */
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of find_peaks *****************************/

/*********************************** m33det ***********************************/
static char doc_f2py_rout_ffind_peaks2_m33det[] = "\
det = m33det(a)\n\nWrapper for ``m33det``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (3,3)\n"
"\nReturns\n-------\n"
"det : float";
/* extern void F_WRAPPEDFUNC(m33det,M33DET)(double*,double*); */
static PyObject *f2py_rout_ffind_peaks2_m33det(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double m33det = 0;
    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    static char *capi_kwlist[] = {"a",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:ffind_peaks2.m33det",\
        capi_kwlist,&a_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
    a_Dims[0]=3,a_Dims[1]=3;
    capi_a_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.m33det: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable m33det */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&m33det,a);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",m33det);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable m33det */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of m33det *******************************/

/****************************** print_real_array ******************************/
static char doc_f2py_rout_ffind_peaks2_print_real_array[] = "\
print_real_array(x,name)\n\nWrapper for ``print_real_array``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"name : input string(len=-1)";
/* extern void F_WRAPPEDFUNC_US(print_real_array,PRINT_REAL_ARRAY)(double*,string,int*,size_t); */
static PyObject *f2py_rout_ffind_peaks2_print_real_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,string,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    string name = NULL;
    int slen(name);
    PyObject *name_capi = Py_None;
    int f2py_x_d0 = 0;
    static char *capi_kwlist[] = {"x","name",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:ffind_peaks2.print_real_array",\
        capi_kwlist,&x_capi,&name_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.print_real_array: failed to create array from the 1st argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (double *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable name */
    slen(name) = -1;
    f2py_success = string_from_pyobj(&name,&slen(name),"",name_capi,"string_from_pyobj failed in converting 2nd argument`name' of ffind_peaks2.print_real_array to C string");
    if (f2py_success) {
        STRINGPADN(name, slen(name), '\0', ' ');
    /* Processing variable f2py_x_d0 */
    f2py_x_d0 = shape(x, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(x,name,&f2py_x_d0,slen(name));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_x_d0 */
        STRINGFREE(name);
    }  /*if (f2py_success) of name*/
    /* End of cleaning variable name */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of print_real_array **************************/

/***************************** print_real_matrix *****************************/
static char doc_f2py_rout_ffind_peaks2_print_real_matrix[] = "\
print_real_matrix(m,name)\n\nWrapper for ``print_real_matrix``.\
\n\nParameters\n----------\n"
"m : input rank-2 array('d') with bounds (f2py_m_d0,f2py_m_d1)\n"
"name : input string(len=-1)";
/* extern void F_WRAPPEDFUNC_US(print_real_matrix,PRINT_REAL_MATRIX)(double*,string,int*,int*,size_t); */
static PyObject *f2py_rout_ffind_peaks2_print_real_matrix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,string,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *m = NULL;
    npy_intp m_Dims[2] = {-1, -1};
    const int m_Rank = 2;
    PyArrayObject *capi_m_as_array = NULL;
    int capi_m_intent = 0;
    PyObject *m_capi = Py_None;
    string name = NULL;
    int slen(name);
    PyObject *name_capi = Py_None;
    int f2py_m_d0 = 0;
    int f2py_m_d1 = 0;
    static char *capi_kwlist[] = {"m","name",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:ffind_peaks2.print_real_matrix",\
        capi_kwlist,&m_capi,&name_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable m */
    ;
    capi_m_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.print_real_matrix: failed to create array from the 1st argument `m`";
    capi_m_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,m_Dims,m_Rank,  capi_m_intent,m_capi,capi_errmess);
    if (capi_m_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        m = (double *)(PyArray_DATA(capi_m_as_array));

    /* Processing variable name */
    slen(name) = -1;
    f2py_success = string_from_pyobj(&name,&slen(name),"",name_capi,"string_from_pyobj failed in converting 2nd argument`name' of ffind_peaks2.print_real_matrix to C string");
    if (f2py_success) {
        STRINGPADN(name, slen(name), '\0', ' ');
    /* Processing variable f2py_m_d0 */
    f2py_m_d0 = shape(m, 0);
    /* Processing variable f2py_m_d1 */
    f2py_m_d1 = shape(m, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(m,name,&f2py_m_d0,&f2py_m_d1,slen(name));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_m_d1 */
    /* End of cleaning variable f2py_m_d0 */
        STRINGFREE(name);
    }  /*if (f2py_success) of name*/
    /* End of cleaning variable name */
    if((PyObject *)capi_m_as_array!=m_capi) {
        Py_XDECREF(capi_m_as_array); }
    }  /* if (capi_m_as_array == NULL) ... else of m */
    /* End of cleaning variable m */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of print_real_matrix **************************/

/******************************** fit_parabola ********************************/
static char doc_f2py_rout_ffind_peaks2_fit_parabola[] = "\
a = fit_parabola(x,y)\n\nWrapper for ``fit_parabola``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (f2py_x_d0)\n"
"y : input rank-1 array('d') with bounds (f2py_y_d0)\n"
"\nReturns\n-------\n"
"a : rank-1 array('d') with bounds (3) and fit_parabola storage";
/* extern void F_WRAPPEDFUNC_US(fit_parabola,FIT_PARABOLA)(double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_ffind_peaks2_fit_parabola(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *fit_parabola = NULL;
    npy_intp fit_parabola_Dims[1] = {-1};
    const int fit_parabola_Rank = 1;
    PyArrayObject *capi_fit_parabola_as_array = NULL;
    int capi_fit_parabola_intent = 0;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_as_array = NULL;
    int capi_y_intent = 0;
    PyObject *y_capi = Py_None;
    int f2py_x_d0 = 0;
    int f2py_y_d0 = 0;
    static char *capi_kwlist[] = {"x","y",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:ffind_peaks2.fit_parabola",\
        capi_kwlist,&x_capi,&y_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.fit_parabola: failed to create array from the 1st argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (double *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable y */
    ;
    capi_y_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.fit_parabola: failed to create array from the 2nd argument `y`";
    capi_y_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,y_Dims,y_Rank,  capi_y_intent,y_capi,capi_errmess);
    if (capi_y_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y = (double *)(PyArray_DATA(capi_y_as_array));

    /* Processing variable fit_parabola */
    fit_parabola_Dims[0]=3;
    capi_fit_parabola_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.fit_parabola: failed to create array from the hidden `fit_parabola`";
    capi_fit_parabola_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fit_parabola_Dims,fit_parabola_Rank,  capi_fit_parabola_intent,Py_None,capi_errmess);
    if (capi_fit_parabola_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fit_parabola = (double *)(PyArray_DATA(capi_fit_parabola_as_array));

    /* Processing variable f2py_x_d0 */
    f2py_x_d0 = shape(x, 0);
    /* Processing variable f2py_y_d0 */
    f2py_y_d0 = shape(y, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(fit_parabola,x,y,&f2py_x_d0,&f2py_y_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_fit_parabola_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_y_d0 */
    /* End of cleaning variable f2py_x_d0 */
    }  /* if (capi_fit_parabola_as_array == NULL) ... else of fit_parabola */
    /* End of cleaning variable fit_parabola */
    if((PyObject *)capi_y_as_array!=y_capi) {
        Py_XDECREF(capi_y_as_array); }
    }  /* if (capi_y_as_array == NULL) ... else of y */
    /* End of cleaning variable y */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of fit_parabola ****************************/

/****************************** refine_positions ******************************/
static char doc_f2py_rout_ffind_peaks2_refine_positions[] = "\
x_m,y_m,p_a = refine_positions(n_close,i_m,x,y,[n,nm])\n\nWrapper for ``refine_positions``.\
\n\nParameters\n----------\n"
"n_close : input int\n"
"i_m : input rank-1 array('i') with bounds (nm)\n"
"x : input rank-1 array('d') with bounds (n)\n"
"y : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(x, 0)\n"
"nm : input int, optional\n    Default: shape(i_m, 0)\n"
"\nReturns\n-------\n"
"x_m : rank-1 array('d') with bounds (nm)\n"
"y_m : rank-1 array('d') with bounds (nm)\n"
"p_a : rank-2 array('d') with bounds (nm,3)";
/* extern void F_FUNC_US(refine_positions,REFINE_POSITIONS)(int*,int*,int*,int*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_ffind_peaks2_refine_positions(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    int nm = 0;
    PyObject *nm_capi = Py_None;
    int n_close = 0;
    PyObject *n_close_capi = Py_None;
    int *i_m = NULL;
    npy_intp i_m_Dims[1] = {-1};
    const int i_m_Rank = 1;
    PyArrayObject *capi_i_m_as_array = NULL;
    int capi_i_m_intent = 0;
    PyObject *i_m_capi = Py_None;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_as_array = NULL;
    int capi_y_intent = 0;
    PyObject *y_capi = Py_None;
    double *x_m = NULL;
    npy_intp x_m_Dims[1] = {-1};
    const int x_m_Rank = 1;
    PyArrayObject *capi_x_m_as_array = NULL;
    int capi_x_m_intent = 0;
    double *y_m = NULL;
    npy_intp y_m_Dims[1] = {-1};
    const int y_m_Rank = 1;
    PyArrayObject *capi_y_m_as_array = NULL;
    int capi_y_m_intent = 0;
    double *p_a = NULL;
    npy_intp p_a_Dims[2] = {-1, -1};
    const int p_a_Rank = 2;
    PyArrayObject *capi_p_a_as_array = NULL;
    int capi_p_a_intent = 0;
    static char *capi_kwlist[] = {"n_close","i_m","x","y","n","nm",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|OO:ffind_peaks2.refine_positions",\
        capi_kwlist,&n_close_capi,&i_m_capi,&x_capi,&y_capi,&n_capi,&nm_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n_close */
        f2py_success = int_from_pyobj(&n_close,n_close_capi,"ffind_peaks2.refine_positions() 1st argument (n_close) can't be converted to int");
    if (f2py_success) {
    /* Processing variable i_m */
    ;
    capi_i_m_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.refine_positions: failed to create array from the 2nd argument `i_m`";
    capi_i_m_as_array = ndarray_from_pyobj(  NPY_INT,1,i_m_Dims,i_m_Rank,  capi_i_m_intent,i_m_capi,capi_errmess);
    if (capi_i_m_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        i_m = (int *)(PyArray_DATA(capi_i_m_as_array));

    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.refine_positions: failed to create array from the 3rd argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (double *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable n */
    if (n_capi == Py_None) n = shape(x, 0); else
        f2py_success = int_from_pyobj(&n,n_capi,"ffind_peaks2.refine_positions() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(x, 0) == n,"shape(x, 0) == n","1st keyword n","refine_positions:n=%d",n) {
    /* Processing variable nm */
    if (nm_capi == Py_None) nm = shape(i_m, 0); else
        f2py_success = int_from_pyobj(&nm,nm_capi,"ffind_peaks2.refine_positions() 2nd keyword (nm) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(i_m, 0) == nm,"shape(i_m, 0) == nm","2nd keyword nm","refine_positions:nm=%d",nm) {
    /* Processing variable y */
    y_Dims[0]=n;
    capi_y_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.refine_positions: failed to create array from the 4th argument `y`";
    capi_y_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,y_Dims,y_Rank,  capi_y_intent,y_capi,capi_errmess);
    if (capi_y_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y = (double *)(PyArray_DATA(capi_y_as_array));

    /* Processing variable x_m */
    x_m_Dims[0]=nm;
    capi_x_m_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.refine_positions: failed to create array from the hidden `x_m`";
    capi_x_m_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_m_Dims,x_m_Rank,  capi_x_m_intent,Py_None,capi_errmess);
    if (capi_x_m_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x_m = (double *)(PyArray_DATA(capi_x_m_as_array));

    /* Processing variable y_m */
    y_m_Dims[0]=nm;
    capi_y_m_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.refine_positions: failed to create array from the hidden `y_m`";
    capi_y_m_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,y_m_Dims,y_m_Rank,  capi_y_m_intent,Py_None,capi_errmess);
    if (capi_y_m_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y_m = (double *)(PyArray_DATA(capi_y_m_as_array));

    /* Processing variable p_a */
    p_a_Dims[0]=nm,p_a_Dims[1]=3;
    capi_p_a_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "ffind_peaks2.ffind_peaks2.refine_positions: failed to create array from the hidden `p_a`";
    capi_p_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,p_a_Dims,p_a_Rank,  capi_p_a_intent,Py_None,capi_errmess);
    if (capi_p_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = ffind_peaks2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        p_a = (double *)(PyArray_DATA(capi_p_a_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n,&nm,&n_close,i_m,x,y,x_m,y_m,p_a);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNN",capi_x_m_as_array,capi_y_m_as_array,capi_p_a_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_p_a_as_array == NULL) ... else of p_a */
    /* End of cleaning variable p_a */
    }  /* if (capi_y_m_as_array == NULL) ... else of y_m */
    /* End of cleaning variable y_m */
    }  /* if (capi_x_m_as_array == NULL) ... else of x_m */
    /* End of cleaning variable x_m */
    if((PyObject *)capi_y_as_array!=y_capi) {
        Py_XDECREF(capi_y_as_array); }
    }  /* if (capi_y_as_array == NULL) ... else of y */
    /* End of cleaning variable y */
    } /*CHECKSCALAR(shape(i_m, 0) == nm)*/
    } /*if (f2py_success) of nm*/
    /* End of cleaning variable nm */
    } /*CHECKSCALAR(shape(x, 0) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    if((PyObject *)capi_i_m_as_array!=i_m_capi) {
        Py_XDECREF(capi_i_m_as_array); }
    }  /* if (capi_i_m_as_array == NULL) ... else of i_m */
    /* End of cleaning variable i_m */
    } /*if (f2py_success) of n_close*/
    /* End of cleaning variable n_close */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of refine_positions **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"find_peaks",-1,{{-1}},0,0,(char *)  F_FUNC_US(find_peaks,FIND_PEAKS),  (f2py_init_func)f2py_rout_ffind_peaks2_find_peaks,doc_f2py_rout_ffind_peaks2_find_peaks},
    {"m33det",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC(m33det,M33DET),  (f2py_init_func)f2py_rout_ffind_peaks2_m33det,doc_f2py_rout_ffind_peaks2_m33det},
    {"print_real_array",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(print_real_array,PRINT_REAL_ARRAY),  (f2py_init_func)f2py_rout_ffind_peaks2_print_real_array,doc_f2py_rout_ffind_peaks2_print_real_array},
    {"print_real_matrix",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(print_real_matrix,PRINT_REAL_MATRIX),  (f2py_init_func)f2py_rout_ffind_peaks2_print_real_matrix,doc_f2py_rout_ffind_peaks2_print_real_matrix},
    {"fit_parabola",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC_US(fit_parabola,FIT_PARABOLA),  (f2py_init_func)f2py_rout_ffind_peaks2_fit_parabola,doc_f2py_rout_ffind_peaks2_fit_parabola},
    {"refine_positions",-1,{{-1}},0,0,(char *)  F_FUNC_US(refine_positions,REFINE_POSITIONS),  (f2py_init_func)f2py_rout_ffind_peaks2_refine_positions,doc_f2py_rout_ffind_peaks2_refine_positions},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "ffind_peaks2",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_ffind_peaks2(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = ffind_peaks2_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module ffind_peaks2 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.0");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'ffind_peaks2' is auto-generated with f2py (version:2.3.0).\nFunctions:\n"
"    n_min,min_pos,n_max,max_pos = find_peaks(np,delta,val,n=shape(val, 0))\n"
"    det = m33det(a)\n"
"    print_real_array(x,name)\n"
"    print_real_matrix(m,name)\n"
"    a = fit_parabola(x,y)\n"
"    x_m,y_m,p_a = refine_positions(n_close,i_m,x,y,n=shape(x, 0),nm=shape(i_m, 0))\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.0");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    ffind_peaks2_error = PyErr_NewException ("ffind_peaks2.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_ffind_peaks2_error", ffind_peaks2_error);
    Py_DECREF(ffind_peaks2_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


    {
      extern double F_FUNC(m33det,M33DET)(void);
      PyObject* o = PyDict_GetItemString(d,"m33det");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_WRAPPEDFUNC(m33det,M33DET),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("m33det");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern void F_FUNC_US(print_real_array,PRINT_REAL_ARRAY)(void);
      PyObject* o = PyDict_GetItemString(d,"print_real_array");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(print_real_array,PRINT_REAL_ARRAY),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("print_real_array");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern void F_FUNC_US(print_real_matrix,PRINT_REAL_MATRIX)(void);
      PyObject* o = PyDict_GetItemString(d,"print_real_matrix");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(print_real_matrix,PRINT_REAL_MATRIX),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("print_real_matrix");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern double F_FUNC_US(fit_parabola,FIT_PARABOLA)(void);
      PyObject* o = PyDict_GetItemString(d,"fit_parabola");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_WRAPPEDFUNC_US(fit_parabola,FIT_PARABOLA),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("fit_parabola");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"ffind_peaks2");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
