# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testLayoutArrayDialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(645, 541)
        self.verticalLayout_Dialog = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_Dialog.setObjectName("verticalLayout_Dialog")
        self.scrollArea_GroupBox = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_GroupBox.setWidgetResizable(True)
        self.scrollArea_GroupBox.setObjectName("scrollArea_GroupBox")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 515))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # was originally self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_ScrollArea = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_ScrollArea.setObjectName("verticalLayout_ScrollArea")
        self.groupBox_Dialog = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        # setup group box
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Dialog.sizePolicy().hasHeightForWidth())
        self.groupBox_Dialog.setSizePolicy(sizePolicy)
        self.groupBox_Dialog.setObjectName("groupBox_Dialog")
        self.verticalLayout_GroupBoxDialog = QtWidgets.QVBoxLayout(self.groupBox_Dialog)
        self.verticalLayout_GroupBoxDialog.setObjectName("verticalLayout_GroupBoxDialog")
        # setup entry one
        self.horizontalLayout_QHBox00 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_QHBox00.setObjectName("horizontalLayout_QHBox00")
        self.label_QHBox00 = QtWidgets.QLabel(self.groupBox_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_QHBox00.sizePolicy().hasHeightForWidth())
        self.label_QHBox00.setSizePolicy(sizePolicy)
        self.label_QHBox00.setObjectName("label_QHBox00")
        self.horizontalLayout_QHBox00.addWidget(self.label_QHBox00)
        self.lineEdit_QHBox00 = QtWidgets.QLineEdit(self.groupBox_Dialog)
        self.lineEdit_QHBox00.setObjectName("lineEdit_QHBox00")
        self.horizontalLayout_QHBox00.addWidget(self.lineEdit_QHBox00)
        self.verticalLayout_GroupBoxDialog.addLayout(self.horizontalLayout_QHBox00)
        # done with entry one next etnry
        self.horizontalLayout_QHBox01 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_QHBox01.setObjectName("horizontalLayout_QHBox01")
        self.label_QHBox01 = QtWidgets.QLabel(self.groupBox_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_QHBox01.sizePolicy().hasHeightForWidth())
        self.label_QHBox01.setSizePolicy(sizePolicy)
        self.label_QHBox01.setObjectName("label_QHBox01")
        self.horizontalLayout_QHBox01.addWidget(self.label_QHBox01)
        self.lineEdit_QHBox01 = QtWidgets.QLineEdit(self.groupBox_Dialog)
        self.lineEdit_QHBox01.setObjectName("lineEdit_QHBox01")
        self.horizontalLayout_QHBox01.addWidget(self.lineEdit_QHBox01)
        self.verticalLayout_GroupBoxDialog.addLayout(self.horizontalLayout_QHBox01)
        # done with 1
        self.horizontalLayout_QHBox02 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_QHBox02.setObjectName("horizontalLayout_QHBox02")
        self.label_QHBox02 = QtWidgets.QLabel(self.groupBox_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_QHBox02.sizePolicy().hasHeightForWidth())
        self.label_QHBox02.setSizePolicy(sizePolicy)
        self.label_QHBox02.setObjectName("label_QHBox02")
        self.horizontalLayout_QHBox02.addWidget(self.label_QHBox02)
        self.lineEdit_QHBox02 = QtWidgets.QLineEdit(self.groupBox_Dialog)
        self.lineEdit_QHBox02.setObjectName("lineEdit_QHBox02")
        self.horizontalLayout_QHBox02.addWidget(self.lineEdit_QHBox02)
        self.verticalLayout_GroupBoxDialog.addLayout(self.horizontalLayout_QHBox02)
        # done with 2
        self.horizontalLayout_QHBox03 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_QHBox03.setObjectName("horizontalLayout_QHBox03")
        self.label_QHBox03 = QtWidgets.QLabel(self.groupBox_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_QHBox03.sizePolicy().hasHeightForWidth())
        self.label_QHBox03.setSizePolicy(sizePolicy)
        self.label_QHBox03.setObjectName("label_QHBox03")
        self.horizontalLayout_QHBox03.addWidget(self.label_QHBox03)
        self.lineEdit_QHBox03 = QtWidgets.QLineEdit(self.groupBox_Dialog)
        self.lineEdit_QHBox03.setObjectName("lineEdit_QHBox03")
        self.horizontalLayout_QHBox03.addWidget(self.lineEdit_QHBox03)
        self.verticalLayout_GroupBoxDialog.addLayout(self.horizontalLayout_QHBox03)
        # done with 3 add cancel and OK buttons
        self.buttonBox_CancelOK = QtWidgets.QDialogButtonBox(self.groupBox_Dialog)
        self.buttonBox_CancelOK.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_CancelOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_CancelOK.setObjectName("buttonBox_CancelOK")
        self.verticalLayout_GroupBoxDialog.addWidget(self.buttonBox_CancelOK)
        # done with the group box add to Scroll area tp ;ayout
        self.verticalLayout_ScrollArea.addWidget(self.groupBox_Dialog)
        self.scrollArea_GroupBox.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_Dialog.addWidget(self.scrollArea_GroupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_Dialog.setTitle(_translate("Dialog", "GroupBox"))
        self.label_QHBox00.setText(_translate("Dialog", "TextLabel"))
        self.label_QHBox01.setText(_translate("Dialog", "TextLabel"))
        self.label_QHBox02.setText(_translate("Dialog", "TextLabel"))
        self.label_QHBox03.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
